import Head from "next/head";
import Image from "next/image";
import { Typography } from "@mui/material";
import { ENV } from "@/env";
import TestButton from "@/components/TestButton";
import ManageAccountButton from "@/components/ManageAccountButton";

interface Props {
  url: string;
  apiKey: string;
  clientId: string;
}

export default function Home({ url, apiKey, clientId }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <TestButton url={url} apiKey={apiKey} clientId={clientId} />
          <ManageAccountButton />
          <Image
            src="/next.svg"
            alt="Next.js logo"
            width={100}
            height={20}
            priority
          />
          <div>
            <Typography variant="h1">
              To get started, edit the index.tsx file.
            </Typography>
            <Typography>
              Looking for a starting point or more instructions? Head over to{" "}
              <a
                href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                Templates
              </a>{" "}
              or the{" "}
              <a
                href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                Learning
              </a>{" "}
              center.
            </Typography>
          </div>
          <div>
            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                src="/vercel.svg"
                alt="Vercel logomark"
                width={16}
                height={16}
              />
              Deploy Now
            </a>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Documentation
            </a>
          </div>
        </main>
      </div>
    </>
  );
}

export const getStaticProps = async () => {
  return {
    props: {
      url: ENV.BETTER_AUTH_URL,
      apiKey: ENV.GOOGLE_API_KEY,
      clientId: ENV.GOOGLE_CLIENT_ID,
    },
  };
};
