import Head from "next/head";
import { ENV } from "@/env";
import TestButton from "@/components/TestButton";
import ManageAccountButton from "@/components/ManageAccountButton";
import CreatePlaylistForm from "@/components/CreatePlaylistForm";
import { useEffect } from "react";
import { setEnvVariables } from "@/lib/utils/envUtils";

interface Props {
  googleApiKey: string;
  googleClientId: string;
}

export default function Home({ googleApiKey, googleClientId }: Props) {
  useEffect(
    () => {
      setEnvVariables(googleApiKey, googleClientId);
    },
    // Dependencies should never change
    // eslint-disable-next-line react-hooks/exhaustive-deps
    []
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <TestButton />
          <ManageAccountButton />
          <CreatePlaylistForm />
        </main>
      </div>
    </>
  );
}

export const getStaticProps = async (): Promise<{ props: Props }> => {
  return {
    props: {
      googleApiKey: ENV.GOOGLE_API_KEY,
      googleClientId: ENV.GOOGLE_CLIENT_ID,
    },
  };
};
