import Head from "next/head";
import { ENV } from "@/env";
import TestButton from "@/components/TestButton";
import ManageAccountButton from "@/components/ManageAccountButton";
import CreatePlaylistForm from "@/components/CreatePlaylistForm";
import Script from "next/script";
import { useCallback, useEffect, useState } from "react";
import { setEnvVariables } from "@/lib/utils/envUtils";
import useIsSignedIn from "@/hooks/useIsSignedIn";
import { initGapiClient } from "@/lib/utils/gapiUtils";

interface Props {
  googleApiKey: string;
  googleClientId: string;
}

export default function Home({ googleApiKey, googleClientId }: Props) {
  const isSignedIn = useIsSignedIn();

  const [isGapiLoaded, setIsGapiLoaded] = useState(false);

  useEffect(
    () => {
      setEnvVariables(googleApiKey, googleClientId);
    },
    // Dependencies should never change
    // eslint-disable-next-line react-hooks/exhaustive-deps
    []
  );

  const initGapi = useCallback(() => {
    if (isSignedIn && isGapiLoaded) {
      initGapiClient();
    }
  }, [isSignedIn, isGapiLoaded]);

  useEffect(() => {
    initGapi();
  }, [initGapi]);

  const handleGapiLoad = () => {
    gapi.load("client", () => {
      setIsGapiLoaded(true);
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="https://apis.google.com/js/api.js" onLoad={handleGapiLoad} />
      <div>
        <main>
          <TestButton />
          <ManageAccountButton />
          <CreatePlaylistForm />
        </main>
      </div>
    </>
  );
}

export const getStaticProps = async (): Promise<{ props: Props }> => {
  return {
    props: {
      googleApiKey: ENV.GOOGLE_API_KEY,
      googleClientId: ENV.GOOGLE_CLIENT_ID,
    },
  };
};
